{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "routify.secretName" . }}
  labels:
    {{- include "routify.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.secrets.dbPassword | default "" | b64enc | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | default "" | b64enc | quote }}
  redis-password: {{ .Values.secrets.redisPassword | default "" | b64enc | quote }}
  jwt-private-key: {{ .Values.secrets.jwtPrivateKey | default "" | b64enc | quote }}
  jwt-public-key: {{ .Values.secrets.jwtPublicKey | default "" | b64enc | quote }}
  cert-vault-encryption-key: {{ .Values.secrets.certVaultEncryptionKey | default "" | b64enc | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | default "" | b64enc | quote }}
{{- end }}

