package gr.routify.ai.config;

import gr.routify.common.event.RabbitTopology;
import org.springframework.amqp.core.*;
import org.springframework.amqp.rabbit.connection.ConnectionFactory;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.amqp.support.converter.Jackson2JsonMessageConverter;
import org.springframework.amqp.support.converter.MessageConverter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * RabbitMQ topology for routify-ai-service.
 *
 * <h3>Role</h3>
 * The AI service is a pure <em>responder</em> in the RPC pattern:
 * <ul>
 *   <li>It owns the {@code routify.ai-service} direct exchange.</li>
 *   <li>It declares and binds the {@code routify.ai-service.filter.evaluate} queue.</li>
 *   <li>The gateway (requester) sends to this exchange with routing key
 *       {@link RabbitTopology#RK_AI_FILTER_EVALUATE}.</li>
 *   <li>Spring AMQP automatically sets the {@code replyTo} header to the
 *       Direct Reply-To pseudo-queue ({@code amq.rabbitmq.reply-to}), so no
 *       explicit reply queue declaration is needed.</li>
 * </ul>
 *
 * <h3>Direct Reply-To topology</h3>
 * <pre>
 * Gateway (producer)
 *   │  To: routify.ai-service exchange
 *   │  RK: ai.filter.evaluate
 *   │  replyTo: amq.rabbitmq.reply-to  (set by RabbitTemplate automatically)
 *   │  correlationId: <auto-generated UUID per call>
 *   ▼
 * routify.ai-service.filter.evaluate (queue)
 *   │  @RabbitListener → AiFilterRpcListener.handleEvaluate()
 *   │  → AiFilterEvaluationService.evaluate()
 *   │  → reply to amq.rabbitmq.reply-to with same correlationId
 *   ▼
 * Gateway receives verdict and resumes reactive pipeline
 * </pre>
 *
 * <h3>No explicit reply queue needed</h3>
 * RabbitMQ's Direct Reply-To feature ({@code amq.rabbitmq.reply-to}) is a pseudo-queue
 * that routes replies directly back to the requesting consumer's connection channel.
 * Spring AMQP's {@link RabbitTemplate#sendAndReceive} uses this automatically.
 */
@Configuration
public class AiRabbitConfig {

    // ─── Exchange ─────────────────────────────────────────────────────────────

    @Bean
    public DirectExchange aiServiceExchange() {
        return ExchangeBuilder
                .directExchange(RabbitTopology.EXCHANGE_AI_SERVICE)
                .durable(true)
                .build();
    }

    // ─── Queues ───────────────────────────────────────────────────────────────

    /**
     * Durable queue for AI filter evaluation requests from the gateway.
     *
     * <p>Durable = survives broker restarts. Requests queued during a brief
     * AI service restart are not lost — they are processed when the service
     * comes back up (within the gateway's reply timeout window).
     *
     * <p>A single queue with default concurrency (configurable via
     * {@code spring.rabbitmq.listener.simple.concurrency}) handles all evaluation
     * requests. Scale horizontally by adding more ai-service pod replicas —
     * RabbitMQ distributes messages across competing consumers automatically.
     */
    @Bean
    public Queue aiFilterEvaluateQueue() {
        return QueueBuilder
                .durable(RabbitTopology.QUEUE_AI_FILTER_EVALUATE)
                .build();
    }

    /**
     * Durable queue for AI modifier evaluation requests from the gateway.
     *
     * <p>Mirrors the filter queue in design — durable, single queue, competing
     * consumers across replicas. The gateway sends mutation requests here and
     * receives the verdict via Direct Reply-To.
     */
    @Bean
    public Queue aiModifierEvaluateQueue() {
        return QueueBuilder
                .durable(RabbitTopology.QUEUE_AI_MODIFIER_EVALUATE)
                .build();
    }

    // ─── Bindings ─────────────────────────────────────────────────────────────

    @Bean
    public Binding aiFilterEvaluateBinding(Queue aiFilterEvaluateQueue,
                                           DirectExchange aiServiceExchange) {
        return BindingBuilder
                .bind(aiFilterEvaluateQueue)
                .to(aiServiceExchange)
                .with(RabbitTopology.RK_AI_FILTER_EVALUATE);
    }

    @Bean
    public Binding aiModifierEvaluateBinding(Queue aiModifierEvaluateQueue,
                                             DirectExchange aiServiceExchange) {
        return BindingBuilder
                .bind(aiModifierEvaluateQueue)
                .to(aiServiceExchange)
                .with(RabbitTopology.RK_AI_MODIFIER_EVALUATE);
    }

    // ─── Message converter & template ─────────────────────────────────────────

    /**
     * Jackson2JsonMessageConverter is used by the auto-configured listener container factory.
     * This allows {@code @RabbitListener} methods to receive
     * {@link gr.routify.common.event.QueryRequest.AiFilterEvaluate} and return
     * {@link gr.routify.common.event.QueryResponse.AiFilterVerdict} without manual
     * JSON serialization.
     */
    @Bean
    public MessageConverter aiJsonMessageConverter() {
        return new Jackson2JsonMessageConverter();
    }

    /**
     * RabbitTemplate for the AI service.
     * Primarily used in tests; production replies go through the listener container.
     */
    @Bean
    public RabbitTemplate aiRabbitTemplate(ConnectionFactory connectionFactory) {
        RabbitTemplate template = new RabbitTemplate(connectionFactory);
        template.setMessageConverter(aiJsonMessageConverter());
        template.setReplyTimeout(RabbitTopology.REPLY_TIMEOUT_MS);
        return template;
    }
}

