{{- if and .Values.routeService.enabled (.Values.routeService.pdb).enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "routify.routeService.fullname" . }}
  labels:
    {{- include "routify.routeService.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.routeService.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "routify.routeService.selectorLabels" . | nindent 6 }}
{{- end }}

