{{- if and .Values.routeService.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "routify.routeService.fullname" . }}
  labels:
    {{- include "routify.routeService.labels" . | nindent 4 }}
  {{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "routify.routeService.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}

