package io.routify.common.web;

/**
 * Central registry of all custom HTTP header names used across Routify services.
 *
 * <h2>Categories</h2>
 * <ul>
 *   <li><b>Auth headers</b> ({@code X-Auth-*}) — propagated by the API-gateway / admin-api JWT
 *       filter to downstream services after validating the bearer token.</li>
 *   <li><b>Tenant header</b> ({@code X-Tenant-Id}) — supplied by the client to scope a request
 *       to a specific tenant workspace.</li>
 *   <li><b>Tracing / observability</b> — correlation ID and route version.</li>
 *   <li><b>Internal</b> — headers used inside the platform that must never reach external
 *       callers (e.g. replay marker).</li>
 *   <li><b>Security-sensitive</b> — header names that are redacted from logs.</li>
 * </ul>
 *
 * <p>All fields are {@code public static final String} so they can be used wherever a
 * header-name string literal is needed: {@code @RequestHeader}, Spring Cloud Gateway
 * filter factories, CORS configuration, log redaction lists, etc.
 */
public final class RoutifyHeaders {

    private RoutifyHeaders() {}

    // ─── Tenant ───────────────────────────────────────────────────────────────

    /**
     * Tenant identifier supplied by the client (or injected from JWT by admin-api).
     * Used by every service to scope queries and enforce tenant isolation.
     */
    public static final String TENANT_ID = "X-Tenant-Id";

    // ─── Auth (JWT-derived, injected by gateway / admin-api) ──────────────────

    /**
     * JWT subject — the authenticated user's UUID string.
     * Injected by the gateway JwtFilter / admin-api JwtAuthFilter after token validation.
     */
    public static final String AUTH_USER_ID = "X-Auth-User-Id";

    /**
     * Tenant claim extracted from the validated JWT.
     * Always set from the JWT (authoritative); used by downstream services for
     * security cross-validation.
     */
    public static final String AUTH_TENANT_ID = "X-Auth-Tenant-Id";

    /**
     * Role claim extracted from the validated JWT (e.g. {@code SUPER_ADMIN}, {@code ADMIN}).
     */
    public static final String AUTH_ROLE = "X-Auth-Role";

    /**
     * Email claim extracted from the validated JWT.
     */
    public static final String AUTH_EMAIL = "X-Auth-Email";

    /**
     * Authentication mechanism used for the current request (e.g. {@code BASIC}, {@code BEARER}).
     * Injected by the BasicAuthGatewayFilterFactory.
     */
    public static final String AUTH_TYPE = "X-Auth-Type";

    /**
     * Explicit user identifier supplied by the caller on write operations.
     * When present it takes precedence over the authenticated principal name
     * as the "actor" for audit purposes. Optional — falls back to the principal
     * name or {@code "system"}.
     *
     * @see #resolveActor(String, String)
     */
    public static final String USER_ID = "X-User-Id";

    // ─── Tracing / observability ──────────────────────────────────────────────

    /**
     * Correlation ID propagated through the entire request chain for log correlation.
     * Generated by the gateway's CorrelationIdGatewayFilterFactory if absent.
     * Exposed in responses so clients can correlate their traces.
     */
    public static final String CORRELATION_ID = "X-Correlation-Id";

    /**
     * Route version tag added to responses by the gateway for cache-busting and
     * client-side diagnostics. Exposed via CORS.
     */
    public static final String ROUTE_VERSION = "X-Route-Version";

    // ─── Internal / platform ──────────────────────────────────────────────────

    /**
     * Marker header set by the audit-service replay mechanism to prevent a replayed
     * request from producing a second audit log entry. Stripped by the gateway before
     * forwarding to the upstream service.
     */
    public static final String REPLAY_MARKER = "X-Routify-Replay";

    // ─── Security-sensitive (redacted from logs) ──────────────────────────────

    /**
     * API key header — treated as a secret credential; redacted from access logs.
     */
    public static final String API_KEY = "X-Api-Key";

    /**
     * Legacy auth-token header — treated as a secret credential; redacted from access logs.
     */
    public static final String AUTH_TOKEN = "X-Auth-Token";

    // ─── Utilities ────────────────────────────────────────────────────────────

    /**
     * Resolves the acting principal for audit / command attribution.
     *
     * <p>Resolution order:
     * <ol>
     *   <li>The {@value #USER_ID} header value when explicitly supplied by the caller.</li>
     *   <li>The authenticated principal name (e.g. {@code Authentication#getName()}).</li>
     *   <li>The literal {@code "system"} fallback for unauthenticated / scheduled calls.</li>
     * </ol>
     *
     * <p>Typical usage in a Spring MVC controller:
     * <pre>{@code
     * String actor = RoutifyHeaders.resolveActor(userId, auth != null ? auth.getName() : null);
     * }</pre>
     *
     * @param userId        the value of the {@value #USER_ID} request header, may be {@code null}
     * @param principalName the authenticated principal name, may be {@code null}
     * @return a non-null, non-blank actor string
     */
    public static String resolveActor(String userId, String principalName) {
        if (userId != null && !userId.isBlank()) return userId;
        return principalName != null ? principalName : "system";
    }
}


